/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        "surface-secondary": "var(--color-surface-secondary)",
        "surface-tertiary": "var(--color-surface-tertiary)",
        border: "var(--color-border)",
        "border-light": "var(--color-border-light)",
        "border-muted": "var(--color-border-muted)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted": "var(--color-text-muted)",
        "text-inverse": "var(--color-text-inverse)",
        "primary-warm": "var(--color-primary-warm)",
        "primary-warm-dark": "var(--color-primary-warm-dark)",
        "primary-warm-light": "var(--color-primary-warm-light)",
        "primary-warm-foreground": "var(--color-primary-warm-foreground)",
        "primary-cool": "var(--color-primary-cool)",
        "primary-cool-dark": "var(--color-primary-cool-dark)",
        "primary-cool-light": "var(--color-primary-cool-light)",
        "primary-cool-foreground": "var(--color-primary-cool-foreground)",
        "secondary-cool": "var(--color-secondary-cool)",
        "secondary-cool-dark": "var(--color-secondary-cool-dark)",
        success: "var(--color-success)",
        "success-dark": "var(--color-success-dark)",
        "success-light": "var(--color-success-light)",
        "success-foreground": "var(--color-success-foreground)",
        error: "var(--color-error)",
        "error-dark": "var(--color-error-dark)",
        "error-light": "var(--color-error-light)",
        "error-foreground": "var(--color-error-foreground)",
        warning: "var(--color-warning)",
        "warning-dark": "var(--color-warning-dark)",
        "warning-light": "var(--color-warning-light)",
        "warning-foreground": "var(--color-warning-foreground)",
        overlay: "var(--color-overlay)",
      },
    },
  },
  plugins: [],
}
